// Priyanshu Shukla All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGamePlayTags
{
	/** Input Tags **/
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	

	/** Player Tags **/
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
}