// Priyanshu Shukla All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGamePlayTags
{
	/** Input Tags **/
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);
	

	/** Player Tags **/
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_AttackEnd);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);
	
	/** Enemy Tags **/
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Defend);

	/** Shared Tags **/
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);

	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	MOBCOMBAT_RPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
}